CREATE TABLE IF NOT EXISTS comptes (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    mot_de_passe VARCHAR(255) NOT NULL,
    date_creation TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
